name: Continuous Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile
        run: mvn install

      - name: Slow tests
        run: mvn test -DskipTests=false -Dgroups=slow
